"""add action settings priority to appliance rules

Revision ID: 3ab07a8e1cd4
Revises: e0bbb0017a7b
Create Date: 2025-11-27 18:23:12.206313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ab07a8e1cd4'
down_revision: Union[str, None] = 'e0bbb0017a7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appliance_condition_rules', sa.Column('action', sa.String(), server_default='on', nullable=False, comment='제어 액션 (on/off/auto)'))
    op.add_column('appliance_condition_rules', sa.Column('settings_json', sa.JSON(), nullable=True, comment='제어 설정값 (온도, 풍속 등)'))
    op.add_column('appliance_condition_rules', sa.Column('priority', sa.Integer(), server_default='1', nullable=False, comment='우선순위 (1이 가장 높음)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appliance_condition_rules', 'priority')
    op.drop_column('appliance_condition_rules', 'settings_json')
    op.drop_column('appliance_condition_rules', 'action')
    # ### end Alembic commands ###
