"""add tracking tables

Revision ID: 63773ec0a32a
Revises: 673442797dd9
Create Date: 2025-11-07 07:40:02.710523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '63773ec0a32a'
down_revision: Union[str, None] = '673442797dd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_observations',
    sa.Column('nx', sa.Integer(), nullable=False),
    sa.Column('ny', sa.Integer(), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('condition_code', sa.String(), nullable=True),
    sa.Column('precip_type', sa.String(), nullable=True),
    sa.Column('temp_c', sa.Float(), nullable=True),
    sa.Column('humidity_pct', sa.Float(), nullable=True),
    sa.Column('wind_speed_mps', sa.Float(), nullable=True),
    sa.Column('pm10', sa.Float(), nullable=True),
    sa.Column('pm2_5', sa.Float(), nullable=True),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('nx', 'ny', 'as_of', 'provider')
    )
    op.create_table('health_hourly',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('ts_hour', sa.DateTime(timezone=True), nullable=False),
    sa.Column('heart_rate_bpm', sa.Float(), nullable=True),
    sa.Column('resting_hr_bpm', sa.Float(), nullable=True),
    sa.Column('walking_hr_avg_bpm', sa.Float(), nullable=True),
    sa.Column('hrv_sdnn_ms', sa.Float(), nullable=True),
    sa.Column('vo2_max', sa.Float(), nullable=True),
    sa.Column('spo2_pct', sa.Float(), nullable=True),
    sa.Column('ecg_index', sa.Float(), nullable=True),
    sa.Column('irregular_rhythm', sa.Boolean(), nullable=True),
    sa.Column('respiratory_rate_cpm', sa.Float(), nullable=True),
    sa.Column('oxygen_saturation_pct', sa.Float(), nullable=True),
    sa.Column('env_audio_db', sa.Float(), nullable=True),
    sa.Column('headphone_audio_db', sa.Float(), nullable=True),
    sa.Column('env_sound_level_db', sa.Float(), nullable=True),
    sa.Column('wrist_temp_c', sa.Float(), nullable=True),
    sa.Column('mindful_min', sa.Float(), nullable=True),
    sa.Column('daylight_min', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('device_model', sa.String(), nullable=True),
    sa.Column('os_version', sa.String(), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'ts_hour', name='uq_health_user_hour')
    )
    op.create_index(op.f('ix_health_hourly_ts_hour'), 'health_hourly', ['ts_hour'], unique=False)
    op.create_index(op.f('ix_health_hourly_user_id'), 'health_hourly', ['user_id'], unique=False)
    op.create_table('places',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('center_lat', sa.Float(), nullable=False),
    sa.Column('center_lon', sa.Float(), nullable=False),
    sa.Column('radius_m', sa.Float(), nullable=False),
    sa.Column('visits_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_places_user_id'), 'places', ['user_id'], unique=False)
    op.create_table('sleep_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('in_bed_hr', sa.Float(), nullable=True),
    sa.Column('asleep_hr', sa.Float(), nullable=True),
    sa.Column('awake_hr', sa.Float(), nullable=True),
    sa.Column('core_hr', sa.Float(), nullable=True),
    sa.Column('deep_hr', sa.Float(), nullable=True),
    sa.Column('rem_hr', sa.Float(), nullable=True),
    sa.Column('respiratory_rate', sa.Float(), nullable=True),
    sa.Column('heart_rate_avg', sa.Float(), nullable=True),
    sa.Column('efficiency', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('device_model', sa.String(), nullable=True),
    sa.Column('os_version', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'start_at', 'end_at', name='uq_sleep_user_period')
    )
    op.create_index(op.f('ix_sleep_sessions_end_at'), 'sleep_sessions', ['end_at'], unique=False)
    op.create_index(op.f('ix_sleep_sessions_start_at'), 'sleep_sessions', ['start_at'], unique=False)
    op.create_index(op.f('ix_sleep_sessions_user_id'), 'sleep_sessions', ['user_id'], unique=False)
    op.create_table('workout_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('workout_type', sa.String(), nullable=False),
    sa.Column('step_count', sa.Integer(), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('flights_climbed', sa.Integer(), nullable=True),
    sa.Column('active_energy_kcal', sa.Float(), nullable=True),
    sa.Column('basal_energy_kcal', sa.Float(), nullable=True),
    sa.Column('exercise_min', sa.Float(), nullable=True),
    sa.Column('stand_hr', sa.Float(), nullable=True),
    sa.Column('stand_hours', sa.Integer(), nullable=True),
    sa.Column('walking_speed_kmh', sa.Float(), nullable=True),
    sa.Column('step_length_cm', sa.Float(), nullable=True),
    sa.Column('walking_asymmetry_pct', sa.Float(), nullable=True),
    sa.Column('double_support_pct', sa.Float(), nullable=True),
    sa.Column('stair_speed_up_dps', sa.Float(), nullable=True),
    sa.Column('stair_speed_down_dps', sa.Float(), nullable=True),
    sa.Column('avg_hr', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('device_model', sa.String(), nullable=True),
    sa.Column('os_version', sa.String(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_sessions_end_at'), 'workout_sessions', ['end_at'], unique=False)
    op.create_index(op.f('ix_workout_sessions_start_at'), 'workout_sessions', ['start_at'], unique=False)
    op.create_index(op.f('ix_workout_sessions_user_id'), 'workout_sessions', ['user_id'], unique=False)
    op.create_table('time_slots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('ts_hour', sa.DateTime(timezone=True), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('altitude', sa.Float(), nullable=True),
    sa.Column('horizontal_accuracy', sa.Float(), nullable=True),
    sa.Column('vertical_accuracy', sa.Float(), nullable=True),
    sa.Column('place_id', sa.UUID(), nullable=True),
    sa.Column('grid_nx', sa.Integer(), nullable=True),
    sa.Column('grid_ny', sa.Integer(), nullable=True),
    sa.Column('weather_provider', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'ts_hour', name='uq_time_slots_user_hour')
    )
    op.create_index(op.f('ix_time_slots_place_id'), 'time_slots', ['place_id'], unique=False)
    op.create_index(op.f('ix_time_slots_ts_hour'), 'time_slots', ['ts_hour'], unique=False)
    op.create_index(op.f('ix_time_slots_user_id'), 'time_slots', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_time_slots_user_id'), table_name='time_slots')
    op.drop_index(op.f('ix_time_slots_ts_hour'), table_name='time_slots')
    op.drop_index(op.f('ix_time_slots_place_id'), table_name='time_slots')
    op.drop_table('time_slots')
    op.drop_index(op.f('ix_workout_sessions_user_id'), table_name='workout_sessions')
    op.drop_index(op.f('ix_workout_sessions_start_at'), table_name='workout_sessions')
    op.drop_index(op.f('ix_workout_sessions_end_at'), table_name='workout_sessions')
    op.drop_table('workout_sessions')
    op.drop_index(op.f('ix_sleep_sessions_user_id'), table_name='sleep_sessions')
    op.drop_index(op.f('ix_sleep_sessions_start_at'), table_name='sleep_sessions')
    op.drop_index(op.f('ix_sleep_sessions_end_at'), table_name='sleep_sessions')
    op.drop_table('sleep_sessions')
    op.drop_index(op.f('ix_places_user_id'), table_name='places')
    op.drop_table('places')
    op.drop_index(op.f('ix_health_hourly_user_id'), table_name='health_hourly')
    op.drop_index(op.f('ix_health_hourly_ts_hour'), table_name='health_hourly')
    op.drop_table('health_hourly')
    op.drop_table('weather_observations')
    # ### end Alembic commands ###
