"""add weather cache table

Revision ID: e0bbb0017a7b
Revises: 81c03ade5e0d
Create Date: 2025-11-27 15:14:17.089644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e0bbb0017a7b'
down_revision: Union[str, None] = '81c03ade5e0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_cache',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('location_key', sa.String(), nullable=False, comment='위도경도 조합 (예: 37.5665_126.9780)'),
    sa.Column('temperature', sa.Float(), nullable=True, comment='기온 (°C)'),
    sa.Column('humidity', sa.Float(), nullable=True, comment='습도 (%)'),
    sa.Column('precipitation', sa.Float(), nullable=True, comment='1시간 강수량 (mm)'),
    sa.Column('wind_speed', sa.Float(), nullable=True, comment='풍속 (m/s)'),
    sa.Column('pm10', sa.Float(), nullable=True, comment='미세먼지 PM10 (㎍/㎥)'),
    sa.Column('pm2_5', sa.Float(), nullable=True, comment='초미세먼지 PM2.5 (㎍/㎥)'),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='조회 시각'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='만료 시각 (보통 10분 후)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_weather_location_fetched', 'weather_cache', ['location_key', 'fetched_at'], unique=False)
    op.create_index(op.f('ix_weather_cache_location_key'), 'weather_cache', ['location_key'], unique=True)
    op.create_table('appliance_command_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('appliance_type', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False, comment='on/off/set'),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('triggered_by', sa.String(), nullable=True, comment='scenario1/scenario2/manual'),
    sa.Column('fatigue_level_used', sa.Integer(), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_command_log_user_executed', 'appliance_command_logs', ['user_id', 'executed_at'], unique=False)
    op.create_index(op.f('ix_appliance_command_logs_user_id'), 'appliance_command_logs', ['user_id'], unique=False)
    op.create_table('appliance_condition_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('fatigue_level', sa.Integer(), nullable=False, comment='피로도 레벨 (1: 좋음, 2: 보통, 3: 나쁨, 4: 매우 나쁨)'),
    sa.Column('appliance_type', sa.String(), nullable=False, comment='가전 종류 (에어컨/가습기/제습기/공기청정기/조명/TV)'),
    sa.Column('condition_json', sa.JSON(), nullable=False, comment='작동 조건'),
    sa.Column('is_enabled', sa.Boolean(), server_default='true', nullable=False, comment='이 규칙 활성화 여부'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_condition_user_fatigue', 'appliance_condition_rules', ['user_id', 'fatigue_level', 'appliance_type'], unique=False)
    op.create_index(op.f('ix_appliance_condition_rules_user_id'), 'appliance_condition_rules', ['user_id'], unique=False)
    op.create_table('appliance_status',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('appliance_type', sa.String(), nullable=False, comment='가전 종류'),
    sa.Column('is_on', sa.Boolean(), server_default='false', nullable=False, comment='전원 상태'),
    sa.Column('current_settings', sa.JSON(), nullable=True, comment='현재 설정값'),
    sa.Column('last_command', sa.JSON(), nullable=True, comment='마지막 명령'),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_appliance_status_user', 'appliance_status', ['user_id', 'appliance_type'], unique=False)
    op.create_index(op.f('ix_appliance_status_user_id'), 'appliance_status', ['user_id'], unique=False)
    op.create_table('fatigue_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False, comment='날짜'),
    sa.Column('avg_hrv', sa.Float(), nullable=True, comment='평균 HRV'),
    sa.Column('avg_fatigue_level', sa.Float(), nullable=True, comment='평균 피로도'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fatigue_history_user_date', 'fatigue_history', ['user_id', 'date'], unique=False)
    op.create_index(op.f('ix_fatigue_history_user_id'), 'fatigue_history', ['user_id'], unique=False)
    op.create_table('geofence_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False, comment='ENTER/EXIT/APPROACHING_DETECTED'),
    sa.Column('distance_from_home', sa.Float(), nullable=False),
    sa.Column('triggered_scenario1', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_geofence_event_user', 'geofence_events', ['user_id', 'event_type', 'created_at'], unique=False)
    op.create_index(op.f('ix_geofence_events_user_id'), 'geofence_events', ['user_id'], unique=False)
    op.create_table('geofence_tracking',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('distance_from_home', sa.Float(), nullable=False, comment='집까지 거리 (미터)'),
    sa.Column('approaching', sa.Boolean(), server_default='false', nullable=False, comment='지속적으로 가까워지는 중'),
    sa.Column('previous_distance', sa.Float(), nullable=True, comment='10분 전 거리'),
    sa.Column('tracked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_geofence_user_tracked', 'geofence_tracking', ['user_id', 'tracked_at'], unique=False)
    op.create_index(op.f('ix_geofence_tracking_user_id'), 'geofence_tracking', ['user_id'], unique=False)
    op.create_table('hrv_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('hrv_value', sa.Float(), nullable=False, comment='HRV 값 (ms)'),
    sa.Column('fatigue_level', sa.Integer(), nullable=False, comment='피로도 레벨 (1: 좋음, 2: 보통, 3: 나쁨, 4: 매우 나쁨)'),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False, comment='애플워치에서 측정한 시각'),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='백엔드에 동기화된 시각'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_hrv_user_measured', 'hrv_logs', ['user_id', 'measured_at'], unique=False)
    op.create_index(op.f('ix_hrv_logs_user_id'), 'hrv_logs', ['user_id'], unique=False)
    op.create_table('stress_assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('stress_level', sa.String(), nullable=False),
    sa.Column('stress_score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('hrv_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stress_assessments_timestamp'), 'stress_assessments', ['timestamp'], unique=False)
    op.create_index(op.f('ix_stress_assessments_user_id'), 'stress_assessments', ['user_id'], unique=False)
    op.create_table('user_appliance_preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('fatigue_level', sa.Integer(), nullable=False, comment='피로도 레벨'),
    sa.Column('appliance_type', sa.String(), nullable=False, comment='가전 종류'),
    sa.Column('settings_json', sa.JSON(), nullable=False, comment='선호 세팅'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_preference_user_fatigue', 'user_appliance_preferences', ['user_id', 'fatigue_level', 'appliance_type'], unique=False)
    op.create_index(op.f('ix_user_appliance_preferences_user_id'), 'user_appliance_preferences', ['user_id'], unique=False)
    op.create_table('user_locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('home_latitude', sa.Float(), nullable=True, comment='집 위도'),
    sa.Column('home_longitude', sa.Float(), nullable=True, comment='집 경도'),
    sa.Column('geofence_radius_meters', sa.Float(), server_default='100.0', nullable=False, comment='Geofence 반경 (미터)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_locations_user_id'), 'user_locations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_locations_user_id'), table_name='user_locations')
    op.drop_table('user_locations')
    op.drop_index(op.f('ix_user_appliance_preferences_user_id'), table_name='user_appliance_preferences')
    op.drop_index('idx_preference_user_fatigue', table_name='user_appliance_preferences')
    op.drop_table('user_appliance_preferences')
    op.drop_index(op.f('ix_stress_assessments_user_id'), table_name='stress_assessments')
    op.drop_index(op.f('ix_stress_assessments_timestamp'), table_name='stress_assessments')
    op.drop_table('stress_assessments')
    op.drop_index(op.f('ix_hrv_logs_user_id'), table_name='hrv_logs')
    op.drop_index('idx_hrv_user_measured', table_name='hrv_logs')
    op.drop_table('hrv_logs')
    op.drop_index(op.f('ix_geofence_tracking_user_id'), table_name='geofence_tracking')
    op.drop_index('idx_geofence_user_tracked', table_name='geofence_tracking')
    op.drop_table('geofence_tracking')
    op.drop_index(op.f('ix_geofence_events_user_id'), table_name='geofence_events')
    op.drop_index('idx_geofence_event_user', table_name='geofence_events')
    op.drop_table('geofence_events')
    op.drop_index(op.f('ix_fatigue_history_user_id'), table_name='fatigue_history')
    op.drop_index('idx_fatigue_history_user_date', table_name='fatigue_history')
    op.drop_table('fatigue_history')
    op.drop_index(op.f('ix_appliance_status_user_id'), table_name='appliance_status')
    op.drop_index('idx_appliance_status_user', table_name='appliance_status')
    op.drop_table('appliance_status')
    op.drop_index(op.f('ix_appliance_condition_rules_user_id'), table_name='appliance_condition_rules')
    op.drop_index('idx_condition_user_fatigue', table_name='appliance_condition_rules')
    op.drop_table('appliance_condition_rules')
    op.drop_index(op.f('ix_appliance_command_logs_user_id'), table_name='appliance_command_logs')
    op.drop_index('idx_command_log_user_executed', table_name='appliance_command_logs')
    op.drop_table('appliance_command_logs')
    op.drop_index(op.f('ix_weather_cache_location_key'), table_name='weather_cache')
    op.drop_index('idx_weather_location_fetched', table_name='weather_cache')
    op.drop_table('weather_cache')
    # ### end Alembic commands ###
